In [2]:
import pandas as pd
import numpy as np

In [2]:
ov = pd.DataFrame({"Year": [], "GW": [], "GWh": [], "Max MW": [], "Mean MW": []})
for yr in np.arange(2015, 2025):
    nskip = 1
    if yr >= 2020:
        nskip = 2
    df = pd.read_excel("../data/eia-860/december_generator"+str(yr)+".xlsx", skiprows = nskip)
    df = df[(df["Technology"] == "Batteries") & (df["Status"] == "(OP) Operating")]
    try:
        # Convert to float, replacing empty strings with 0
        arr = df["Nameplate Energy Capacity (MWh)"]
        arr_numeric = np.where(arr == " ", 0, arr).astype(float)
    except:
        arr_numeric = np.array(0)
    try:
        ov.loc[len(ov)] = [yr, df["Nameplate Capacity (MW)"].sum()/1000, arr_numeric.sum()/1000, max(df["Nameplate Capacity (MW)"]), np.mean(df["Nameplate Capacity (MW)"])]
    except:
        print(str(yr) + " does not have nameplate capacity or energy capacity")

2015 does not have nameplate capacity or energy capacity
2016 does not have nameplate capacity or energy capacity
2017 does not have nameplate capacity or energy capacity

In [3]:
ov

     Year       GW      GWh  Max MW    Mean MW
0  2018.0   0.8375   0.0000    40.0   7.219828
1  2019.0   1.0143   0.0000    40.0   6.339375
2  2020.0   1.6218   0.0000   250.0   7.950000
3  2021.0   4.5989   0.0000   409.0  14.507571
4  2022.0   8.7903  11.0302   409.0  21.079856
5  2023.0  15.3237  26.2726   409.0  27.912022
6  2024.0  26.1457  71.2033   409.0  35.332027

In [3]:
yr = 2024
df = pd.read_excel("../data/eia-860/december_generator"+str(yr)+".xlsx", skiprows = 2, sheet_name = "Planned")
df = df[(df["Technology"] == "Batteries")]
planned_total = df.groupby("Planned Operation Year")["Nameplate Capacity (MW)"].sum()/1000
planned_max = df.groupby("Planned Operation Year")["Nameplate Capacity (MW)"].max()
planned_mean = df.groupby("Planned Operation Year")["Nameplate Capacity (MW)"].mean()

In [5]:
bat_power = pd.DataFrame({"Year": [], "Operating (GW)": [], "Operating max (MW)": [], "Operating mean (MW)": [], "Planned (GW)": [],
                        "Planned max (MW)": [], "Planned mean (MW)": []})
for yr in np.arange(2018, 2031):
    try:
        op_total = ov[ov["Year"] == yr]["GW"].values[0]
        op_max = ov[ov["Year"] == yr]["Max MW"].values[0]
        op_mean = ov[ov["Year"] == yr]["Mean MW"].values[0]
    except:
        op = ov["GW"].iloc[-1]
        op_max = ov["Max MW"].iloc[-1]
        op_mean = ov["Mean MW"].iloc[-1]
    if yr >= 2025:
        planned = planned_total[2025:yr].sum()
        bat_power.loc[len(bat_power)] = [int(yr), op_total, op_max, op_mean, planned, planned_max[yr], planned_mean[yr]]
    else:
        bat_power.loc[len(bat_power)] = [int(yr), op_total, op_max, op_mean, 0, 0, 0]

C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()

In [6]:
bat_power

,Year,Operating (GW),Operating max (MW),Operating mean (MW),Planned (GW),Planned max (MW),Planned mean (MW)
0,2018.0,0.8375,40.0,7.219828,0.0000,0.0,0.000000
1,2019.0,1.0143,40.0,6.339375,0.0000,0.0,0.000000
2,2020.0,1.6218,250.0,7.950000,0.0000,0.0,0.000000
3,2021.0,4.5989,409.0,14.507571,0.0000,0.0,0.000000
4,2022.0,8.7903,409.0,21.079856,0.0000,0.0,0.000000
5,2023.0,15.3237,409.0,27.912022,0.0000,0.0,0.000000
6,2024.0,26.1457,409.0,35.332027,0.0000,0.0,0.000000
7,2025.0,26.1457,409.0,35.332027,18.1670,500.0,89.492611
8,2026.0,26.1457,409.0,35.332027,34.9138,621.4,126.869697
9,2027.0,26.1457,409.0,35.332027,51.1502,1200.0,198.004878
10,2028.0,26.1457,409.0,35.332027,58.3901,1400.0,241.330000
11,2029.0,26.1457,409.0,35.332027,59.6901,1000.0,650.000000
12,2030.0,26.1457,409.0,35.332027,60.4901,400.0,400.000000

In [7]:
df[(df["Technology"] == "Batteries") & (df["Status"] == "(OP) Operating")]

Empty DataFrame
Columns: [Entity ID, Entity Name, Plant ID, Plant Name, Google Map, Bing Map, Plant State, County, Balancing Authority Code, Sector, Generator ID, Unit Code, Nameplate Capacity (MW), Net Summer Capacity (MW), Net Winter Capacity (MW), Technology, Energy Source Code, Prime Mover Code, Planned Operation Month, Planned Operation Year, Status, Latitude, Longitude]
Index: []

[0 rows x 23 columns]

Current generation

In [4]:
df = pd.read_excel("../data/eia-860/december_generator2024.xlsx")
df.columns = df.iloc[1]
df.drop([0,1], inplace = True)

In [10]:
for i in df.columns:
    print(i)

Entity ID
Entity Name
Plant ID
Plant Name
Google Map
Bing Map
Plant State
County
Balancing Authority Code
Sector
Generator ID
Unit Code
Nameplate Capacity (MW)
Net Summer Capacity (MW)
Net Winter Capacity (MW)
Technology
Energy Source Code
Prime Mover Code
Operating Month
Operating Year
Planned Retirement Month
Planned Retirement Year
Status
Nameplate Energy Capacity (MWh)
DC Net Capacity (MW)
Planned Derate Year
Planned Derate Month
Planned Derate of Summer Capacity (MW)
Planned Uprate Year
Planned Uprate Month
Planned Uprate of Summer Capacity (MW)
Latitude
Longitude

In [5]:
# Balancing authorities that are ISOs:
iso_list = ["MISO", "PJM", "CISO", "ISNE", "ERCO", "NYIS", "SWPP"]
# https://www.gridinfo.com/balancing-authorities?o=plants&d=desc

In [6]:
df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list))]["Sector"].unique()

array(['IPP Non-CHP', 'Electric Utility', 'IPP CHP', 'Commercial CHP',
       'Industrial CHP', 'Commercial Non-CHP', 'Industrial Non-CHP'],
      dtype=object)

In [8]:
results = dict({"Ownership": ["All", "Utility", "IPP Non-CHP"], 
                "Number": [len(df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list)) & (df["Status"] == "(OP) Operating")]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Status"] == "(OP) Operating")]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Status"] == "(OP) Operating")])
                          ], 
                "Power (MW)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Status"] == "(OP) Operating")]["Nameplate Capacity (MW)"].sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Status"] == "(OP) Operating")]["Nameplate Capacity (MW)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Status"] == "(OP) Operating")]["Nameplate Capacity (MW)"].sum(), 2)
                ], 
                "Energy (MWh)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)
                ]})

C:\Users\dirkl\AppData\Local\Temp\ipykernel_4076\1346986293.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2),
C:\Users\dirkl\AppData\Local\Temp\ipykernel_4076\1346986293.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)

In [9]:
pd.DataFrame(results)

     Ownership  Number  Power (MW)  Energy (MWh)
0          All     588     20253.0       52844.4
1      Utility      79      1013.1        3235.0
2  IPP Non-CHP     478     19175.9       49423.7

In [17]:
3.2/52.9

0.06049149338374291

Nantucket

In [6]:
df[df["County"] == "Nantucket"]

1,Entity ID,Entity Name,Plant ID,Plant Name,Google Map,Bing Map,Plant State,County,Balancing Authority Code,Sector,...,Nameplate Energy Capacity (MWh),DC Net Capacity (MW),Planned Derate Year,Planned Derate Month,Planned Derate of Summer Capacity (MW),Planned Uprate Year,Planned Uprate Month,Planned Uprate of Summer Capacity (MW),Latitude,Longitude
2560,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,,,,,,,,,41.2583,-70.0517
2561,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,,,,,,,,,41.2583,-70.0517
2562,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,48,,,,,,,,41.2583,-70.0517

Deregulated states

In [34]:
np.sort(df["Plant State"].unique()[:-1])

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [11]:
# https://quickelectricity.com/deregulated-energy-states/, Oregon is deregulated for electricity but not for gas
deregulated_states = ['CA', 'CT', 'DE', 'GA', 'IL', 'ME', 'MD', 'MA', 'MI', 'NH', 'NJ', 'NY', 'OH', 'PA', 'RI', 'TX', 'VA', 'DC', 'OR']

In [12]:
results = dict({"Ownership": ["All", "Utility", "IPP Non-CHP"], 
                "Number": [len(df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list)) & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")])
                          ], 
                "Power (MW)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Capacity (MW)"].sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Capacity (MW)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Capacity (MW)"].sum(), 2)
                ], 
                "Energy (MWh)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)
                ]})
pd.DataFrame(results)

C:\Users\dirkl\AppData\Local\Temp\ipykernel_4076\3916488217.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2),
C:\Users\dirkl\AppData\Local\Temp\ipykernel_4076\3916488217.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)

     Ownership  Number  Power (MW)  Energy (MWh)
0          All     543     19750.3       51312.9
1      Utility      56       886.8        2901.0
2  IPP Non-CHP     458     18811.5       48252.4

In [43]:
len(deregulated_states)

19

In [14]:
df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")]
#df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility") & (df["Plant State"].isin(deregulated_states))].to_excel("../data/deregulated_utility_batteries.xlsx", index=False, engine="openpyxl")

1,Entity ID,Entity Name,Plant ID,Plant Name,Google Map,Bing Map,Plant State,County,Balancing Authority Code,Sector,...,Nameplate Energy Capacity (MWh),DC Net Capacity (MW),Planned Derate Year,Planned Derate Month,Planned Derate of Summer Capacity (MW),Planned Uprate Year,Planned Uprate Month,Planned Uprate of Summer Capacity (MW),Latitude,Longitude
2560,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,48,,,,,,,,41.2583,-70.0517
2593,18488,City of Taunton,1682,Cleary Flood Hybrid,Map,Map,MA,Bristol,ISNE,Electric Utility,...,6,,,,,,,,41.8653,-71.1061
4272,3542,Duke Energy Ohio Inc,2830,Walter C Beckjord,Map,Map,OH,Clermont,PJM,Electric Utility,...,1,,,,,,,,38.9917,-84.2981
4273,3542,Duke Energy Ohio Inc,2830,Walter C Beckjord,Map,Map,OH,Clermont,PJM,Electric Utility,...,0.8,,,,,,,,38.9917,-84.2981
6967,17609,Southern California Edison Co,6704,Pebbly Beach Generating Station Hybrid,Map,Map,CA,Los Angeles,CISO,Electric Utility,...,6.8,,,,,,,,33.333056,-118.3103
13572,17609,Southern California Edison Co,56472,Grapeland Hybrid,Map,Map,CA,San Bernardino,CISO,Electric Utility,...,10,,,,,,,,34.0903,-117.5343
13576,17609,Southern California Edison Co,56475,Center Hybrid,Map,Map,CA,Los Angeles,CISO,Electric Utility,...,10,,,,,,,,33.9296,-118.1046
18674,5248,Dominion Energy Inc.,60316,Scott Solar Farm,Map,Map,VA,Powhatan,PJM,Electric Utility,...,48,,,,,,,,37.523,-77.934
18939,60336,SDGE Batteries,60565,Borrego Springs Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,1.5,,,,,,,,33.27011,-116.3496
18940,60336,SDGE Batteries,60565,Borrego Springs Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,3,,,,,,,,33.27011,-116.3496
18942,60336,SDGE Batteries,60567,Ortega Highway Energy Storage,Map,Map,CA,Orange,CISO,Electric Utility,...,3,,,,,,,,33.562061,-117.5438
18944,60336,SDGE Batteries,60568,Canyon Crest Academy,Map,Map,CA,San Diego,CISO,Electric Utility,...,3,,,,,,,,32.95907,-117.1916
18945,16609,San Diego Gas & Electric Co,60569,El Cajon Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,30,,,,,,,,32.8115,-117.0505
18946,16609,San Diego Gas & Electric Co,60570,Escondido Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,120,,,,,,,,33.124446,-117.1143
19034,17609,Southern California Edison Co,60661,Mira Loma Energy Storage Facility,Map,Map,CA,San Bernardino,CISO,Electric Utility,...,40,,,,,,,,34.006125,-117.5609
19035,17609,Southern California Edison Co,60661,Mira Loma Energy Storage Facility,Map,Map,CA,San Bernardino,CISO,Electric Utility,...,40,,,,,,,,34.006125,-117.5609
19210,796,Arizona Electric Pwr Coop Inc,60791,SunAnza,Map,Map,CA,Riverside,CISO,Electric Utility,...,4,,,,,,,,33.555267,-116.6396
19211,796,Arizona Electric Pwr Coop Inc,60791,SunAnza,Map,Map,CA,Riverside,CISO,Electric Utility,...,5.2,,,,,,,,33.555267,-116.6396
19404,58375,Sterling Municipal Light Department,60959,Chocksett Rd Energy Storage Project,Map,Map,MA,Worcester,ISNE,Electric Utility,...,3.9,,,,,,,,42.451836,-71.73775
19556,60336,SDGE Batteries,61107,Vanadium Redox Flow Battery Plant,Map,Map,CA,San Diego,CISO,Electric Utility,...,8,,,,,,,,32.682506,-116.9888
19817,16609,San Diego Gas & Electric Co,61365,Fallbrook Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,40,,,,,,,,33.384244,-117.2353
19818,16609,San Diego Gas & Electric Co,61366,Top Gun Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,120,,,,,,,,32.876198,-117.1678
19997,61091,Hopewell Valley High School,61473,Hopewell Valley High School Hybrid,Map,Map,NJ,Mercer,PJM,Electric Utility,...,1,,,,,,,,40.328005,-74.8049
20376,1015,Austin Energy,61741,Kingsberry Energy Storage System,Map,Map,TX,Travis,ERCO,Electric Utility,...,3,,,,,,,,30.266028,-97.68614
20565,4254,Consumers Energy Co - (MI),61909,Parkview Battery,Map,Map,MI,Kalamazoo,MISO,Electric Utility,...,1,,,,,,,,42.26,-85.64972
20655,61576,Ameren Illinois,61990,TAC-Distributed Energy Resource Hybrid,Map,Map,IL,Champaign,MISO,Electric Utility,...,0.5,,,,,,,,40.089797,-88.24357
20700,61597,Caldwell Wastewater Treatment Plant,62027,Caldwell Wastewater Treatment Plant Hybr,Map,Map,NJ,Essex,PJM,Electric Utility,...,2,,,,,,,,40.838568,-74.31248
20892,11806,Massachusetts Mun Wholes Electric Co,62219,Ashburnham Energy Storage Project,Map,Map,MA,Worcester,ISNE,Electric Utility,...,3,,,,,,,,42.671444,-71.9267
20931,2144,Town of Braintree - (MA),62257,Station 9 Energy Storage System,Map,Map,MA,Norfolk,ISNE,Electric Utility,...,4.2,,,,,,,,42.187743,-70.97645
21127,17609,Southern California Edison Co,62460,DESI-2 Battery Storage Facility,Map,Map,CA,Orange,CISO,Electric Utility,...,3.7,,,,,,,,33.7357,-117.9153
21222,14328,Pacific Gas & Electric Co.,62564,Elkhorn Battery Energy Storage System,Map,Map,CA,Monterey,CISO,Electric Utility,...,730,,,,,,,,36.808039,-121.7818
21249,11806,Massachusetts Mun Wholes Electric Co,62585,Beebe Substation Battery Storage,Map,Map,MA,Middlesex,ISNE,Electric Utility,...,3,,,,,,,,42.48791,-71.04781
21274,16604,City of San Antonio - (TX),62609,Commerce ESS,Map,Map,TX,Bexar,ERCO,Electric Utility,...,10,,,,,,,,29.43445,-98.61765
21551,4226,Consolidated Edison Co-NY Inc,62839,98th Street Battery Storage Station,Map,Map,NY,Queens,NYIS,Electric Utility,...,12,,,,,,,,40.679137,-73.84019
21695,56404,National Grid,62981,East Pulaski BESS,Map,Map,NY,Oswego,NYIS,Electric Utility,...,4.2,,,,,,,,43.546613,-76.10403
21942,15296,New York Power Authority,63238,Willis Battery Storage,Map,Map,NY,Franklin,NYIS,Electric Utility,...,20,,,,,,,,44.887905,-74.11828
22025,17609,Southern California Edison Co,63325,Yorktown Battery Energy Storage Facility,Map,Map,CA,Los Angeles,CISO,Electric Utility,...,9,,,,,,,,34.00467,-118.0684
22026,17609,Southern California Edison Co,63326,Cadillac Battery Energy Storage Facility,Map,Map,CA,Los Angeles,CISO,Electric Utility,...,8.8,,,,,,,,34.00469,-118.0684
22332,14154,Orange & Rockland Utils Inc,63585,NY3 Battery,Map,Map,NY,Rockland,NYIS,Electric Utility,...,12,,,,,,,,41.18512,-74.07467
23391,16609,San Diego Gas & Electric Co,64612,Kearny North Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,40,,,,,,,,32.83347,-117.1344
23392,16609,San Diego Gas & Electric Co,64614,Kearny South Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,40,,,,,,,,32.832886,-117.1323
23533,60868,Redwood Coast Energy Authority,64766,Redwood Coast Airport Microgrid,Map,Map,CA,Humboldt,CISO,Electric Utility,...,8.8,,,,,,,,40.967222,-124.1044
23966,4254,Consumers Energy Co - (MI),65029,Bissell Solar and Battery Generator,Map,Map,MI,Kent,MISO,Electric Utility,...,0.5,,,,,,,,43.007,-85.724
23976,4226,Consolidated Edison Co-NY Inc,65035,Fox Hills Battery Station,Map,Map,NY,Richmond,NYIS,Electric Utility,...,30,,,,,,,,40.61081,-74.07717
23984,5248,Dominion Energy Inc.,65044,Dry Bridge Storage,Map,Map,VA,Chesterfield,PJM,Electric Utility,...,80,,,,,,,,37.5,-77.7
24360,17609,Southern California Edison Co,65456,Separator (Etiwanda) BESS,Map,Map,CA,San Bernardino,CISO,Electric Utility,...,450,,,,,,,,34.09211,-117.534
24361,17609,Southern California Edison Co,65457,Cathode (Hinson) BESS,Map,Map,CA,Los Angeles,CISO,Electric Utility,...,400,,,,,,,,33.7763,-118.2003
24362,17609,Southern California Edison Co,65457,Cathode (Hinson) BESS,Map,Map,CA,Los Angeles,CISO,Electric Utility,...,400,,,,,,,,33.7763,-118.2003
24372,15477,Public Service Elec & Gas Co,65468,Highland Park Borough Solar,Map,Map,NJ,Middlesex,PJM,Electric Utility,...,2.1,,,,,,,,40.4966,-74.41746
25280,16609,San Diego Gas & Electric Co,66265,Paradise Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,32.70363,-117.0498
25281,16609,San Diego Gas & Electric Co,66266,Clairemont Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,32.825604,-117.1832
25293,16609,San Diego Gas & Electric Co,66278,Elliott Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,32.81638,-117.0889
25294,16609,San Diego Gas & Electric Co,66279,Boulevard Energy Storage,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,32.66184,-116.2734
25295,16609,San Diego Gas & Electric Co,66280,Pala Gomez Creek BESS,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,33.357667,-117.1117
25296,16609,San Diego Gas & Electric Co,66281,Melrose BESS,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,33.207233,-117.2528
25297,16609,San Diego Gas & Electric Co,66281,Melrose BESS,Map,Map,CA,San Diego,CISO,Electric Utility,...,10,,,,,,,,33.207233,-117.2528

In [18]:
my_cols = ['Nameplate Capacity (MW)', 'Nameplate Energy Capacity (MWh)']
df[(df["Technology"] == "Batteries") & (df["Sector"] == "Electric Utility") & (df["Plant State"].isin(deregulated_states)) & (df["Status"] == "(OP) Operating")].groupby('Plant State')[my_cols].sum()

1           Nameplate Capacity (MW) Nameplate Energy Capacity (MWh)
Plant State
CA                            805.5                          2635.8
GA                             65.2                           260.4
IL                              0.3                             0.5
MA                               19                            68.1
MI                              1.4                             1.5
NJ                              2.6                             5.1
NY                             34.5                            78.2
OH                                4                             1.8
OR                               92                             334
TX                             11.5                              13
VA                               60                             128