In [1]:
import pandas as pd
import numpy as np

In [2]:
ov = pd.DataFrame({"Year": [], "GW": [], "GWh": [], "Max MW": [], "Mean MW": []})
for yr in np.arange(2015, 2025):
    nskip = 1
    if yr >= 2020:
        nskip = 2
    df = pd.read_excel("../data/eia-860/december_generator"+str(yr)+".xlsx", skiprows = nskip)
    df = df[(df["Technology"] == "Batteries") & (df["Status"] == "(OP) Operating")]
    try:
        # Convert to float, replacing empty strings with 0
        arr = df["Nameplate Energy Capacity (MWh)"]
        arr_numeric = np.where(arr == " ", 0, arr).astype(float)
    except:
        arr_numeric = np.array(0)
    try:
        ov.loc[len(ov)] = [yr, df["Nameplate Capacity (MW)"].sum()/1000, arr_numeric.sum()/1000, max(df["Nameplate Capacity (MW)"]), np.mean(df["Nameplate Capacity (MW)"])]
    except:
        print(str(yr) + " does not have nameplate capacity or energy capacity")

2015 does not have nameplate capacity or energy capacity
2016 does not have nameplate capacity or energy capacity
2017 does not have nameplate capacity or energy capacity

In [3]:
ov

     Year       GW      GWh  Max MW    Mean MW
0  2018.0   0.8375   0.0000    40.0   7.219828
1  2019.0   1.0143   0.0000    40.0   6.339375
2  2020.0   1.6218   0.0000   250.0   7.950000
3  2021.0   4.5989   0.0000   409.0  14.507571
4  2022.0   8.7903  11.0302   409.0  21.079856
5  2023.0  15.3237  26.2726   409.0  27.912022
6  2024.0  26.1457  71.2033   409.0  35.332027

In [4]:
yr = 2024
df = pd.read_excel("../data/eia-860/december_generator"+str(yr)+".xlsx", skiprows = 2, sheet_name = "Planned")
df = df[(df["Technology"] == "Batteries")]
planned_total = df.groupby("Planned Operation Year")["Nameplate Capacity (MW)"].sum()/1000
planned_max = df.groupby("Planned Operation Year")["Nameplate Capacity (MW)"].max()
planned_mean = df.groupby("Planned Operation Year")["Nameplate Capacity (MW)"].mean()

In [5]:
bat_power = pd.DataFrame({"Year": [], "Operating (GW)": [], "Operating max (MW)": [], "Operating mean (MW)": [], "Planned (GW)": [],
                        "Planned max (MW)": [], "Planned mean (MW)": []})
for yr in np.arange(2018, 2031):
    try:
        op_total = ov[ov["Year"] == yr]["GW"].values[0]
        op_max = ov[ov["Year"] == yr]["Max MW"].values[0]
        op_mean = ov[ov["Year"] == yr]["Mean MW"].values[0]
    except:
        op = ov["GW"].iloc[-1]
        op_max = ov["Max MW"].iloc[-1]
        op_mean = ov["Mean MW"].iloc[-1]
    if yr >= 2025:
        planned = planned_total[2025:yr].sum()
        bat_power.loc[len(bat_power)] = [int(yr), op_total, op_max, op_mean, planned, planned_max[yr], planned_mean[yr]]
    else:
        bat_power.loc[len(bat_power)] = [int(yr), op_total, op_max, op_mean, 0, 0, 0]

C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\3164440068.py:13: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  planned = planned_total[2025:yr].sum()

In [6]:
bat_power

,Year,Operating (GW),Operating max (MW),Operating mean (MW),Planned (GW),Planned max (MW),Planned mean (MW)
0,2018.0,0.8375,40.0,7.219828,0.0000,0.0,0.000000
1,2019.0,1.0143,40.0,6.339375,0.0000,0.0,0.000000
2,2020.0,1.6218,250.0,7.950000,0.0000,0.0,0.000000
3,2021.0,4.5989,409.0,14.507571,0.0000,0.0,0.000000
4,2022.0,8.7903,409.0,21.079856,0.0000,0.0,0.000000
5,2023.0,15.3237,409.0,27.912022,0.0000,0.0,0.000000
6,2024.0,26.1457,409.0,35.332027,0.0000,0.0,0.000000
7,2025.0,26.1457,409.0,35.332027,18.1670,500.0,89.492611
8,2026.0,26.1457,409.0,35.332027,34.9138,621.4,126.869697
9,2027.0,26.1457,409.0,35.332027,51.1502,1200.0,198.004878
10,2028.0,26.1457,409.0,35.332027,58.3901,1400.0,241.330000
11,2029.0,26.1457,409.0,35.332027,59.6901,1000.0,650.000000
12,2030.0,26.1457,409.0,35.332027,60.4901,400.0,400.000000

In [7]:
df[(df["Technology"] == "Batteries") & (df["Status"] == "(OP) Operating")]

Empty DataFrame
Columns: [Entity ID, Entity Name, Plant ID, Plant Name, Google Map, Bing Map, Plant State, County, Balancing Authority Code, Sector, Generator ID, Unit Code, Nameplate Capacity (MW), Net Summer Capacity (MW), Net Winter Capacity (MW), Technology, Energy Source Code, Prime Mover Code, Planned Operation Month, Planned Operation Year, Status, Latitude, Longitude]
Index: []

[0 rows x 23 columns]

In [9]:
df = pd.read_excel("../data/eia-860/december_generator2024.xlsx")
df.columns = df.iloc[1]
df.drop([0,1], inplace = True)

In [10]:
for i in df.columns:
    print(i)

Entity ID
Entity Name
Plant ID
Plant Name
Google Map
Bing Map
Plant State
County
Balancing Authority Code
Sector
Generator ID
Unit Code
Nameplate Capacity (MW)
Net Summer Capacity (MW)
Net Winter Capacity (MW)
Technology
Energy Source Code
Prime Mover Code
Operating Month
Operating Year
Planned Retirement Month
Planned Retirement Year
Status
Nameplate Energy Capacity (MWh)
DC Net Capacity (MW)
Planned Derate Year
Planned Derate Month
Planned Derate of Summer Capacity (MW)
Planned Uprate Year
Planned Uprate Month
Planned Uprate of Summer Capacity (MW)
Latitude
Longitude

In [11]:
# Balancing authorities that are ISOs:
iso_list = ["MISO", "PJM", "CISO", "ISNE", "ERCO", "NYIS", "SWPP"]
# https://www.gridinfo.com/balancing-authorities?o=plants&d=desc

In [12]:
df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list))]["Sector"].unique()

array(['IPP Non-CHP', 'Electric Utility', 'IPP CHP', 'Commercial CHP',
       'Industrial CHP', 'Commercial Non-CHP', 'Industrial Non-CHP'],
      dtype=object)

In [13]:
results = dict({"Ownership": ["All", "Utility", "IPP Non-CHP"], 
                "Number": [len(df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list))]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")])
                          ], 
                "Power (MW)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list)]["Nameplate Capacity (MW)"].sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]["Nameplate Capacity (MW)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")]["Nameplate Capacity (MW)"].sum(), 2)
                ], 
                "Energy (MWh)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list)]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]["Nameplate Energy Capacity (MWh)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)
                ]})

C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\1062058367.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list)]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2),
C:\Users\dirkl\AppData\Local\Temp\ipykernel_7236\1062058367.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)

In [14]:
pd.DataFrame(results)

     Ownership  Number  Power (MW)  Energy (MWh)
0          All     594     20285.0       52878.1
1      Utility      82      1016.1        3241.0
2  IPP Non-CHP     481     19204.9       49451.4

In [17]:
3.2/52.9

0.06049149338374291

Nantucket

In [6]:
df[df["County"] == "Nantucket"]

1,Entity ID,Entity Name,Plant ID,Plant Name,Google Map,Bing Map,Plant State,County,Balancing Authority Code,Sector,...,Nameplate Energy Capacity (MWh),DC Net Capacity (MW),Planned Derate Year,Planned Derate Month,Planned Derate of Summer Capacity (MW),Planned Uprate Year,Planned Uprate Month,Planned Uprate of Summer Capacity (MW),Latitude,Longitude
2560,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,,,,,,,,,41.2583,-70.0517
2561,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,,,,,,,,,41.2583,-70.0517
2562,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,48,,,,,,,,41.2583,-70.0517

In [18]:
df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]

1,Entity ID,Entity Name,Plant ID,Plant Name,Google Map,Bing Map,Plant State,County,Balancing Authority Code,Sector,...,Nameplate Energy Capacity (MWh),DC Net Capacity (MW),Planned Derate Year,Planned Derate Month,Planned Derate of Summer Capacity (MW),Planned Uprate Year,Planned Uprate Month,Planned Uprate of Summer Capacity (MW),Latitude,Longitude
1667,9273,AES Indiana,990,Harding Street,Map,Map,IN,Marion,MISO,Electric Utility,...,20,,,,,,,,39.711319,-86.19687
2560,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,48,,,,,,,,41.2583,-70.0517
2593,18488,City of Taunton,1682,Cleary Flood Hybrid,Map,Map,MA,Bristol,ISNE,Electric Utility,...,6,,,,,,,,41.8653,-71.1061
4272,3542,Duke Energy Ohio Inc,2830,Walter C Beckjord,Map,Map,OH,Clermont,PJM,Electric Utility,...,1,,,,,,,,38.9917,-84.2981
4273,3542,Duke Energy Ohio Inc,2830,Walter C Beckjord,Map,Map,OH,Clermont,PJM,Electric Utility,...,0.8,,,,,,,,38.9917,-84.2981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25988,13683,North Carolina El Member Corp,67036,Davistown-Mercer,Map,Map,NC,Edgecombe,PJM,Electric Utility,...,5,,,,,,,,35.84423,-77.61267
25989,13683,North Carolina El Member Corp,67037,Medoc,Map,Map,NC,Halifax,PJM,Electric Utility,...,5,,,,,,,,36.24805,-77.85024
26061,14127,Omaha Public Power District,67122,BRIGHT Battery,Map,Map,NE,Cass,SWPP,Electric Utility,...,2.4,,,,,,,,40.871407,-96.17904
26398,66219,Cavalry Energy Center LLC,67489,Cavalry Solar Hybrid,Map,Map,IN,White,MISO,Electric Utility,...,180,,,,,,,,40.895314,-86.81023
26652,4363,Corn Belt Power Coop,67948,Hampton Substation Energy Storage,Map,Map,IA,Franklin,SWPP,Electric Utility,...,9.1,,,,,,,,42.6872,-93.2321

In [19]:
df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")]

1,Entity ID,Entity Name,Plant ID,Plant Name,Google Map,Bing Map,Plant State,County,Balancing Authority Code,Sector,...,Nameplate Energy Capacity (MWh),DC Net Capacity (MW),Planned Derate Year,Planned Derate Month,Planned Derate of Summer Capacity (MW),Planned Uprate Year,Planned Uprate Month,Planned Uprate of Summer Capacity (MW),Latitude,Longitude
468,54802,Dynegy -Moss Landing LLC,260,Dynegy Moss Landing Power Plant Hybrid,Map,Map,CA,Monterey,CISO,IPP Non-CHP,...,1200,,,,,,,,36.804837,-121.7822
469,54802,Dynegy -Moss Landing LLC,260,Dynegy Moss Landing Power Plant Hybrid,Map,Map,CA,Monterey,CISO,IPP Non-CHP,...,400,,,,,,,,36.804837,-121.7822
470,54802,Dynegy -Moss Landing LLC,260,Dynegy Moss Landing Power Plant Hybrid,Map,Map,CA,Monterey,CISO,IPP Non-CHP,...,1400,,,,,,,,36.804837,-121.7822
2419,39006,Brookfield White Pine Hydro LLC,1482,Bonny Eagle,Map,Map,ME,York,ISNE,IPP Non-CHP,...,16,,,,,,,,43.687688,-70.61155
2461,31719,FPL Energy Wyman LLC,1507,William F Wyman Hybrid,Map,Map,ME,Cumberland,ISNE,IPP Non-CHP,...,10.9,,,,,,,,43.7508,-70.1567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26622,58871,Citizens Enterprises Corporation,67899,PNY BESS LLC,Map,Map,PA,Philadelphia,PJM,IPP Non-CHP,...,6.2,,,,,,,,39.89023,-75.18554
26676,66580,"Old Frontier Solar III PV, LLC",68069,Old Frontier Solar III,Map,Map,MA,Franklin,ISNE,IPP Non-CHP,...,,,,,,,,,42.494046,-72.62251
26681,5504,Vistra Corp,68147,Coffeen Solar BESS,Map,Map,IL,Montgomery,MISO,IPP Non-CHP,...,,,,,,,,,39.068994,-89.39336
26683,5504,Vistra Corp,68148,Baldwin Solar BESS,Map,Map,IL,Randolph,MISO,IPP Non-CHP,...,,,,,,,,,38.203536,-89.85394
26705,60520,SoCore Energy LLC,68266,North Juvenile Detention Center Solar,Map,Map,CA,Tulare,CISO,IPP Non-CHP,...,,,,,,,,,36.461,-119.32

In [34]:
np.sort(df["Plant State"].unique()[:-1])

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [ ]:
# https://quickelectricity.com/deregulated-energy-states/, Oregon is deregulated for electricity but not for gas
deregulated_states = ['CA', 'CT', 'DE', 'GA', 'IL', 'ME', 'MD', 'MA', 'MI', 'NH', 'NJ', 'NY', 'OH', 'PA', 'RI', 'TX', 'VA', 'DC', 'OR']