In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../data/august_generator2024.xlsx")
df.columns = df.iloc[1]
df.drop([0,1], inplace = True)

In [3]:
for i in df.columns:
    print(i)

Entity ID
Entity Name
Plant ID
Plant Name
Google Map
Bing Map
Plant State
County
Balancing Authority Code
Sector
Generator ID
Unit Code
Nameplate Capacity (MW)
Net Summer Capacity (MW)
Net Winter Capacity (MW)
Technology
Energy Source Code
Prime Mover Code
Operating Month
Operating Year
Planned Retirement Month
Planned Retirement Year
Status
Nameplate Energy Capacity (MWh)
DC Net Capacity (MW)
Planned Derate Year
Planned Derate Month
Planned Derate of Summer Capacity (MW)
Planned Uprate Year
Planned Uprate Month
Planned Uprate of Summer Capacity (MW)
Latitude
Longitude

In [17]:
# Balancing authorities that are ISOs:
iso_list = ["MISO", "PJM", "CISO", "ISNE", "ERCO", "NYIS", "SWPP"]
# https://www.gridinfo.com/balancing-authorities?o=plants&d=desc

In [26]:
df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list))]["Sector"].unique()

array(['IPP Non-CHP', 'Electric Utility', 'IPP CHP', 'Commercial CHP',
       'Industrial CHP', 'Commercial Non-CHP', 'Industrial Non-CHP'],
      dtype=object)

In [77]:
results = dict({"Ownership": ["All", "Utility", "IPP Non-CHP"], 
                "Number": [len(df[(df["Technology"] == "Batteries") & (df["Balancing Authority Code"].isin(iso_list))]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]),
                           len(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")])
                          ], 
                "Power (MW)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list)]["Nameplate Capacity (MW)"].sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]["Nameplate Capacity (MW)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")]["Nameplate Capacity (MW)"].sum(), 2)
                ], 
                "Energy (MWh)": [
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list)]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2), 
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "Electric Utility")]["Nameplate Energy Capacity (MWh)"].sum(), 2),
                    round(df[(df["Technology"] == "Batteries") & df["Balancing Authority Code"].isin(iso_list) & (df["Sector"] == "IPP Non-CHP")]["Nameplate Energy Capacity (MWh)"].replace(" ", 0).sum(), 2)
                ]})

In [79]:
pd.DataFrame(results)

     Ownership  Number  Power (MW)  Energy (MWh)
0          All     537     16754.5       45052.0
1      Utility      74       690.3        1954.1
2  IPP Non-CHP     432     16000.2       42912.2

Nantucket

In [6]:
df[df["County"] == "Nantucket"]

1,Entity ID,Entity Name,Plant ID,Plant Name,Google Map,Bing Map,Plant State,County,Balancing Authority Code,Sector,...,Nameplate Energy Capacity (MWh),DC Net Capacity (MW),Planned Derate Year,Planned Derate Month,Planned Derate of Summer Capacity (MW),Planned Uprate Year,Planned Uprate Month,Planned Uprate of Summer Capacity (MW),Latitude,Longitude
2560,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,,,,,,,,,41.2583,-70.0517
2561,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,,,,,,,,,41.2583,-70.0517
2562,13206,Nantucket Electric Co,1615,Nantucket Hybrid,Map,Map,MA,Nantucket,ISNE,Electric Utility,...,48,,,,,,,,41.2583,-70.0517